name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      -main

jobs:
  Deplopy-development:
    runs-on: ubuntu-latest
    
    steps:
      - name: "checkout code"
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: action/setup-node@v4

      - name: Install npm
        uses: action/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'http://registry.npmjs.org/'

      - name: Install dependecies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercelk@latest

      - name: Pull Vercel Enviroment Information
        run: vercel pull --yes --enviroment=deployment --token=${{secrets.ACCESS_TOKEN_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token${{secrets.ACCESS_TOKEN_ID}}\

      - name: Deploy Projects Artifacts to Vercel
        run: vercel deploly --prebuilt --prod --token=${{secrets.ACCESS_TOKEN_ID}}

        

      

        
      
        
